package com.steven.solomon.code;

public interface FileErrorCode extends BaseExceptionCode {

  String NO_STORAGE_IMPLEMENTATION = "NO_STORAGE_IMPLEMENTATION";

  String MORE_THAN_THE_SHARING_TIME = "MORE_THAN_THE_SHARING_TIME";

  String FILE_DOWNLOAD_ERROR = "FILE_DOWNLOAD_ERROR";

  String METHOD_NOT_IMPLEMENTED = "METHOD_NOT_IMPLEMENTED";
}
