<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.steven</groupId>
        <artifactId>solomon-parent</artifactId>
        <version>1.0</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>solomon-cloud-module</artifactId>
    <name>Solomon Cloud Module</name>
    <description>微服务聚合模块，包含服务发现（Nacos）、RPC（Dubbo）、分布式事务（Seata）、限流熔断（Sentinel）。</description>
    <packaging>pom</packaging>

    <modules>
        <module>solomon-cloud-sdk</module>
        <module>solomon-nacos</module>
        <module>solomon-dubbo</module>
        <module>solomon-seata</module>
        <module>solomon-sentinel</module>
    </modules>

</project>
