<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.steven</groupId>
    <artifactId>solomon-persistence-module</artifactId>
    <version>1.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>

  <artifactId>solomon-persistence-sdk</artifactId>
  <description>关系型数据库持久化公共 SDK</description>

  <dependencies>
    <dependency>
      <groupId>com.steven</groupId>
      <artifactId>solomon-base</artifactId>
    </dependency>
    <dependency>
      <groupId>com.steven</groupId>
      <artifactId>solomon-utils-core</artifactId>
    </dependency>
  </dependencies>
</project>
