package com.steven.solomon.code;

public interface PowerJobErrorCode extends BaseExceptionCode {

  String POWER_JOB_JOB_ID_IS_NULL = "POWER_JOB_JOB_ID_IS_NULL";

  String POWER_JOB_TASK_IS_NULL = "POWER_JOB_TASK_IS_NULL";

  String POWER_JOB_URL_NULL = "POWER_JOB_URL_NULL";

  String POWER_JOB_USER_NAME_NULL = "POWER_JOB_USER_NAME_NULL";

  String POWER_JOB_PASSWORD_NULL = "POWER_JOB_PASSWORD_NULL";

  String POWER_JOB_EXECUTE_POST_ERROR = "POWER_JOB_EXECUTE_POST_ERROR";

  String POWER_JOB_EXECUTE_GET_ERROR = "POWER_JOB_EXECUTE_GET_ERROR";
}
