i18n:
  all-locale: zh,en
  language: zh
  path: i18n/messages
server:
  port: 8001
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  group-configs:
    - group: default
      paths-to-match: /**
      packages-to-scan: com.steven
knife4j:
  enable: true
  setting:
    language: zh_cn
solomon:
  swagger:
    enabled: true
    title: rabbitmq测试用例
    version: 1.0.0
    global-request-parameters:
      - name: token
        in: header
        description: 用户认证令牌
        required: true
        hidden: false
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jmx:
    enabled: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    auto-delete-queue: false
    enabled: false
